[package]
name = "travel-rs"
version = "0.1.1"
authors = ["Michele Medori <princeofborgo@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.13.0", features = ["macros"] }
log = "0.4.25"
tokio = { version =  "1.43.0", features = ["rt-multi-thread", "macros"] }
rust_decimal = "1.36.0"
surrealdb = "2.2.1"
config = "0.15.8"
anyhow = "1.0.95"
serde = "1.0.217"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["local-time", "env-filter"] }
macro_rules_attribute = "0.2.0"
regex = "1.11.1"
strum = { version = "0.27.1", features = ["derive"] }
chrono = "0.4.39"
rust-fuzzy-search = "0.1.1"
travel-rs-derive = { version = "0.1.0", path = "travel-rs-derive" }
