# Bot =========================================================================

    # token_mode: Specifies the mode in which the bot token is provided.
    # Allowed values:
    # - "file": The token is read from a file.
    # - "env": The token is read from an environment variable.
    # - "string": The token is provided directly as a string.
    token_mode = "file"

    # token: The bot token.
    # If token_mode is "file", this should be a path to a file containing the token.
    # If token_mode is "env", this should be the name of the environment variable containing the token.
    # If token_mode is "string", this should be the token itself.
    token = "token.txt"

# =============================================================================

# Database ====================================================================

    db_host = "127.0.0.1"
    db_port = 8000
    db_username = "root"
    db_password = "root"
    db_namespace = "travel_rs"
    db_database = "travel_rs_db"

# =============================================================================
